# Generated by Django 5.0.6 on 2024-06-16 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('album', models.CharField(max_length=250)),
                ('singer', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('song_img', models.ImageField(upload_to='images/')),
                ('song_file', models.FileField(upload_to='uploads/')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
